### ISSUE TITLE
When I try to export a chart

### ISSUE THREAD

**Issue by bmsmaster** [itsLevande/GCCompanion#1]
Error

export/structs/trackPieceArray.lua:9: attempt to get length of local 'trackPieces' (a nil value)

Traceback

[love "callbacks.lua"]:228: in function 'handler'
export/structs/trackPieceArray.lua:9: in function 'new'
export/scene.lua:89: in function 'toStageFile'
main.lua:108: in function 'update'
[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'

**Comment by itsLevande** [comment]
It appears that either `courseline.csv` is not present in `%AppData% > Roaming > GCCompanion`, or some other error has caused that file to not be able to be read from. Would you be able to upload your `courseline.csv` file for me to look at?

**Comment by bmsmaster** [comment]
I figured that it's missing now. I'm looking to make Simple and Normal charts for Sincronicity, along with keysounds (i.e. song stems in the SHOT file).

**Comment by bmsmaster** [comment]
Also, how do I extract the DATs of preexisting songs I want to edit?

**Comment by itsLevande** [comment]
GCCompanion only supports the creation of new charts, not the modification of existing ones. Maybe in the future I'll add such functionality, but for now it's only a one-way process.
