### ISSUE TITLE
Is this a bug or is it my part?

### ISSUE THREAD

**Issue by bmsmaster** [itsLevande/GCCompanion#2]
Error

export/structs/noteExtArray.lua:31: attempt to index a nil value

Traceback

[love "callbacks.lua"]:228: in function 'handler'
export/structs/noteExtArray.lua:31: in function 'new'
export/scene.lua:156: in function 'toStageFile'
main.lua:108: in function 'update'
[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'

**Comment by itsLevande** [comment]
No, that's definitely a bug. It seems I forgot to check if there were any ext notes to begin with. _ext file is only needed when there are Dual Slides, so the program will still output a correct stage file if there are no Dual Slides, but it will crash.

**Comment by itsLevande** [comment]
I've pushed out a new [release](https://github.com/itsLevande/GCCompanion/releases/tag/v0.10a) that prevents this crash.
