### ISSUE TITLE
TUNE_stage Macro

### ISSUE THREAD

**Issue by bmsmaster** [itsLevande/GCCompanion#3]
I use LibreOffice Calc to access the macro. I get an error when I try to access the macro for the stage_param. What should I do to make it work properly?

**Comment by bmsmaster** [comment]
I'm trying to give 1llusion 0f the FAIRYtALE hARMONY staff credits.

**Comment by itsLevande** [comment]
Use Microsoft Excel, since I can guarantee the macro works on that program.
